export type ProviderTier = 'major' | 'regional' | 'niche';

export interface Provider {
  id: number;
  slug: string;
  name: string;
  logo: string;
  color: string;
  gradient: string;
  bgAccent: string;
  borderColor: string;
  tagline: string;
  region: string;
  hasTrending: boolean;
  categories: ('movie' | 'tv')[];
  tier: ProviderTier;
}

export const PROVIDERS: Provider[] = [
  // MAJOR GLOBAL
  {
    id: 8,
    slug: 'netflix',
    name: 'Netflix',
    logo: '/logos/netflix.jpg',
    color: '#E50914',
    gradient: 'from-[#E50914]/40 to-black',
    bgAccent: '#1a0000',
    borderColor: 'border-[#E50914]/30',
    tagline: 'Watch anywhere. Cancel anytime.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 9,
    slug: 'prime-video',
    name: 'Prime Video',
    logo: '/logos/prime-video.jpg',
    color: '#00A8E1',
    gradient: 'from-[#00A8E1]/40 to-black',
    bgAccent: '#001a24',
    borderColor: 'border-[#00A8E1]/30',
    tagline: 'Great shows. Unlimited delivery.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 337,
    slug: 'disney-plus',
    name: 'Disney+',
    logo: '/logos/disney-plus.jpg',
    color: '#113CCF',
    gradient: 'from-[#113CCF]/40 to-black',
    bgAccent: '#02061f',
    borderColor: 'border-[#113CCF]/30',
    tagline: 'The greatest stories, all in one place.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 1899,
    slug: 'max',
    name: 'Max',
    logo: '/logos/max.jpg',
    color: '#002BE7',
    gradient: 'from-[#002BE7]/40 to-black',
    bgAccent: '#000424',
    borderColor: 'border-[#002BE7]/30',
    tagline: 'The one to watch.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 350,
    slug: 'apple-tv-plus',
    name: 'Apple TV+',
    logo: '/logos/apple-tv-plus.jpg',
    color: '#ffffff',
    gradient: 'from-white/30 to-black',
    bgAccent: '#111111',
    borderColor: 'border-white/20',
    tagline: 'All Apple Originals.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 15,
    slug: 'hulu',
    name: 'Hulu',
    logo: '/logos/hulu.jpg',
    color: '#1CE783',
    gradient: 'from-[#1CE783]/40 to-black',
    bgAccent: '#022414',
    borderColor: 'border-[#1CE783]/30',
    tagline: 'All the TV you love.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 531,
    slug: 'paramount-plus',
    name: 'Paramount+',
    logo: '/logos/paramount-plus.jpg',
    color: '#0064FF',
    gradient: 'from-[#0064FF]/40 to-black',
    bgAccent: '#000f26',
    borderColor: 'border-[#0064FF]/30',
    tagline: 'A Mountain of Entertainment.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },

  // REGIONAL POWERHOUSES
  {
    id: 122,
    slug: 'hotstar',
    name: 'Hotstar',
    logo: '/logos/hotstar.jpg',
    color: '#0f065e',
    gradient: 'from-[#0f065e]/60 to-black',
    bgAccent: '#020112',
    borderColor: 'border-[#0f065e]/50',
    tagline: 'Entertainment ka Naya Daur.',
    region: 'IN',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 220,
    slug: 'jiocinema',
    name: 'JioCinema',
    logo: '/logos/jiocinema.svg',
    color: '#C6007E',
    gradient: 'from-[#C6007E]/40 to-black',
    bgAccent: '#1c0012',
    borderColor: 'border-[#C6007E]/30',
    tagline: 'Watch sports, movies, and TV shows.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 237,
    slug: 'sonyliv',
    name: 'SonyLIV',
    logo: '/logos/sonyliv.jpg',
    color: '#00B1B0',
    gradient: 'from-[#00B1B0]/40 to-black',
    bgAccent: '#001a1a',
    borderColor: 'border-[#00B1B0]/30',
    tagline: 'We LIV to Entertain.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 232,
    slug: 'zee5',
    name: 'ZEE5',
    logo: '/logos/zee5.jpg',
    color: '#8230C6',
    gradient: 'from-[#8230C6]/40 to-black',
    bgAccent: '#13071f',
    borderColor: 'border-[#8230C6]/30',
    tagline: 'Anytime. Anywhere.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 283,
    slug: 'crunchyroll',
    name: 'Crunchyroll',
    logo: '/logos/crunchyroll.jpg',
    color: '#F47521',
    gradient: 'from-[#F47521]/40 to-black',
    bgAccent: '#241004',
    borderColor: 'border-[#F47521]/30',
    tagline: 'Everything Anime.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 381,
    slug: 'canal-plus',
    name: 'Canal+',
    logo: '/logos/canal-plus.jpg',
    color: '#000000',
    gradient: 'from-zinc-800/60 to-black',
    bgAccent: '#111111',
    borderColor: 'border-zinc-700/50',
    tagline: 'Créateur de contenu.',
    region: 'FR',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 76,
    slug: 'viaplay',
    name: 'Viaplay',
    logo: '/logos/viaplay.jpg',
    color: '#FF1232',
    gradient: 'from-[#FF1232]/40 to-black',
    bgAccent: '#1f0003',
    borderColor: 'border-[#FF1232]/30',
    tagline: 'Nordic storytelling.',
    region: 'SE',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 38,
    slug: 'stan',
    name: 'Stan',
    logo: '/logos/stan.jpg',
    color: '#0061FF',
    gradient: 'from-[#0061FF]/40 to-black',
    bgAccent: '#000e26',
    borderColor: 'border-[#0061FF]/30',
    tagline: 'The biggest new releases.',
    region: 'AU',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 49,
    slug: 'u-next',
    name: 'U-NEXT',
    logo: '/logos/u-next.svg',
    color: '#21C4D4',
    gradient: 'from-[#21C4D4]/40 to-black',
    bgAccent: '#031c1e',
    borderColor: 'border-[#21C4D4]/30',
    tagline: 'Unlimited entertainment.',
    region: 'JP',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 356,
    slug: 'wavve',
    name: 'Wavve',
    logo: '/logos/wavve.jpg',
    color: '#013DFF',
    gradient: 'from-[#013DFF]/40 to-black',
    bgAccent: '#000926',
    borderColor: 'border-[#013DFF]/30',
    tagline: 'Just dive in.',
    region: 'KR',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 151,
    slug: 'britbox',
    name: 'BritBox',
    logo: '/logos/britbox.jpg',
    color: '#000B2B',
    gradient: 'from-[#000B2B]/80 to-black',
    bgAccent: '#000105',
    borderColor: 'border-[#000B2B]/50',
    tagline: 'The biggest collection of British TV.',
    region: 'UK',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },

  // NICHE / FREE
  {
    id: 73,
    slug: 'tubi-tv',
    name: 'Tubi',
    logo: '/logos/tubi-tv.jpg',
    color: '#FF4F00',
    gradient: 'from-[#FF4F00]/40 to-black',
    bgAccent: '#260c00',
    borderColor: 'border-[#FF4F00]/30',
    tagline: 'Free movies and TV.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 300,
    slug: 'pluto-tv',
    name: 'Pluto TV',
    logo: '/logos/pluto-tv.jpg',
    color: '#F3E400',
    gradient: 'from-[#F3E400]/20 to-black',
    bgAccent: '#242200',
    borderColor: 'border-[#F3E400]/20',
    tagline: 'Drop in. It\'s free.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 11,
    slug: 'mubi',
    name: 'MUBI',
    logo: '/logos/mubi.jpg',
    color: '#15065e',
    gradient: 'from-[#15065e]/60 to-black',
    bgAccent: '#03010f',
    borderColor: 'border-[#15065e]/50',
    tagline: 'Hand-picked cinema.',
    region: 'US',
    hasTrending: false,
    categories: ['movie'],
    tier: 'niche',
  },
  {
    id: 99,
    slug: 'shudder',
    name: 'Shudder',
    logo: '/logos/shudder.jpg',
    color: '#FF0000',
    gradient: 'from-red-600/40 to-black',
    bgAccent: '#1a0000',
    borderColor: 'border-red-600/30',
    tagline: 'Scream-worthy horror.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 258,
    slug: 'criterion-channel',
    name: 'Criterion Channel',
    logo: '/logos/criterion-channel.jpg',
    color: '#8A7D6C',
    gradient: 'from-[#8A7D6C]/40 to-black',
    bgAccent: '#141210',
    borderColor: 'border-[#8A7D6C]/30',
    tagline: 'Classic and contemporary films.',
    region: 'US',
    hasTrending: false,
    categories: ['movie'],
    tier: 'niche',
  },
  {
    id: 538,
    slug: 'plex',
    name: 'Plex',
    logo: '/logos/plex.jpg',
    color: '#EBAF00',
    gradient: 'from-[#EBAF00]/30 to-black',
    bgAccent: '#241b00',
    borderColor: 'border-[#EBAF00]/20',
    tagline: 'Your media, your way.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 190,
    slug: 'curiosity-stream',
    name: 'Curiosity Stream',
    logo: '/logos/curiosity-stream.jpg',
    color: '#FFB81C',
    gradient: 'from-[#FFB81C]/30 to-black',
    bgAccent: '#261b04',
    borderColor: 'border-[#FFB81C]/20',
    tagline: 'Feed your curiosity.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 386,
    slug: 'peacock',
    name: 'Peacock',
    logo: '/logos/peacock.jpg',
    color: '#00A850',
    gradient: 'from-[#00A850]/40 to-black',
    bgAccent: '#001a0c',
    borderColor: 'border-[#00A850]/30',
    tagline: 'Watch for free. Upgrade for more.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 269,
    slug: 'funimation',
    name: 'Funimation',
    logo: '/logos/funimation.svg',
    color: '#5B0BB5',
    gradient: 'from-[#5B0BB5]/50 to-black',
    bgAccent: '#0d011a',
    borderColor: 'border-[#5B0BB5]/40',
    tagline: 'Anime for everyone.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 188,
    slug: 'youtube-premium',
    name: 'YouTube Premium',
    logo: '/logos/youtube-premium.jpg',
    color: '#FF0000',
    gradient: 'from-red-600/40 to-black',
    bgAccent: '#1a0000',
    borderColor: 'border-red-600/30',
    tagline: 'Ad-free and offline.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 344,
    slug: 'rakuten-viki',
    name: 'Rakuten Viki',
    logo: '/logos/rakuten-viki.jpg',
    color: '#0862d0',
    gradient: 'from-[#0862d0]/40 to-black',
    bgAccent: '#010e1f',
    borderColor: 'border-[#0862d0]/30',
    tagline: 'Global Asian Entertainment.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 97,
    slug: 'watcha',
    name: 'Watcha',
    logo: '/logos/watcha.jpg',
    color: '#FF0558',
    gradient: 'from-[#FF0558]/40 to-black',
    bgAccent: '#26000d',
    borderColor: 'border-[#FF0558]/30',
    tagline: 'Find your next favorite.',
    region: 'KR',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 218,
    slug: 'eros-now',
    name: 'Eros Now',
    logo: '/logos/eros-now.svg',
    color: '#F48220',
    gradient: 'from-[#F48220]/40 to-black',
    bgAccent: '#241305',
    borderColor: 'border-[#F48220]/30',
    tagline: 'Bollywood and beyond.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 226,
    slug: 'mx-player',
    name: 'MX Player',
    logo: '/logos/mx-player.svg',
    color: '#0033CC',
    gradient: 'from-[#0033CC]/40 to-black',
    bgAccent: '#00081f',
    borderColor: 'border-[#0033CC]/30',
    tagline: 'Everytainment.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 121,
    slug: 'voot',
    name: 'Voot',
    logo: '/logos/voot.svg',
    color: '#8A2BE2',
    gradient: 'from-[#8A2BE2]/40 to-black',
    bgAccent: '#140621',
    borderColor: 'border-[#8A2BE2]/30',
    tagline: 'Premium Indian content.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 235,
    slug: 'altbalaji',
    name: 'ALTT',
    logo: '/logos/altbalaji.jpg',
    color: '#E82A3A',
    gradient: 'from-[#E82A3A]/40 to-black',
    bgAccent: '#240608',
    borderColor: 'border-[#E82A3A]/30',
    tagline: 'Original stories.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 584,
    slug: 'discovery-plus',
    name: 'discovery+',
    logo: '/logos/discovery-plus.jpg',
    color: '#000000',
    gradient: 'from-blue-600/30 to-black',
    bgAccent: '#000a1a',
    borderColor: 'border-blue-600/30',
    tagline: 'Real life entertainment.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 149,
    slug: 'espn-plus',
    name: 'ESPN+',
    logo: '/logos/espn-plus.jpg',
    color: '#E31837',
    gradient: 'from-[#E31837]/40 to-black',
    bgAccent: '#210308',
    borderColor: 'border-[#E31837]/30',
    tagline: 'Live sports and originals.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 43,
    slug: 'starz',
    name: 'Starz',
    logo: '/logos/starz.jpg',
    color: '#000000',
    gradient: 'from-zinc-800/40 to-black',
    bgAccent: '#111111',
    borderColor: 'border-zinc-700/30',
    tagline: 'Obsessable.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 37,
    slug: 'showtime',
    name: 'Showtime',
    logo: '/logos/showtime.svg',
    color: '#E50914',
    gradient: 'from-red-700/40 to-black',
    bgAccent: '#1f0000',
    borderColor: 'border-red-700/30',
    tagline: 'Pushing boundaries.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 526,
    slug: 'amc-plus',
    name: 'AMC+',
    logo: '/logos/amc-plus.jpg',
    color: '#D4AF37',
    gradient: 'from-[#D4AF37]/30 to-black',
    bgAccent: '#1f1a08',
    borderColor: 'border-[#D4AF37]/20',
    tagline: 'The best of AMC.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 87,
    slug: 'acorn-tv',
    name: 'Acorn TV',
    logo: '/logos/acorn-tv.jpg',
    color: '#1A4F41',
    gradient: 'from-[#1A4F41]/50 to-black',
    bgAccent: '#020d0a',
    borderColor: 'border-[#1A4F41]/40',
    tagline: 'World-class mysteries.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
];
