export type ProviderTier = 'major' | 'regional' | 'niche';

export interface Provider {
  id: number | string;
  slug: string;
  name: string;
  logo: string;
  color: string;
  gradient: string;
  bgAccent: string;
  borderColor: string;
  tagline: string;
  region: string;
  hasTrending: boolean;
  categories: ('movie' | 'tv')[];
  tier: ProviderTier;
}

export const PROVIDERS: Provider[] = [
  // MAJOR GLOBAL
  {
    id: 8,
    slug: 'netflix',
    name: 'Netflix',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Netflix-new-icon.png',
    color: '#E50914',
    gradient: 'from-[#E50914]/40 to-black',
    bgAccent: '#1a0000',
    borderColor: 'border-[#E50914]/30',
    tagline: 'Watch anywhere. Cancel anytime.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 9,
    slug: 'prime-video',
    name: 'Prime Video',
    logo: 'https://image.tmdb.org/t/p/original/pvske1MyAoymrs5bguRfVqYiM9a.jpg',
    color: '#00A8E1',
    gradient: 'from-[#00A8E1]/40 to-black',
    bgAccent: '#001a24',
    borderColor: 'border-[#00A8E1]/30',
    tagline: 'Great shows. Unlimited delivery.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 337,
    slug: 'disney-plus',
    name: 'Disney+',
    logo: 'https://image.tmdb.org/t/p/original/97yvRBw1GzX7fXprcF80er19ot.jpg',
    color: '#113CCF',
    gradient: 'from-[#113CCF]/40 to-black',
    bgAccent: '#02061f',
    borderColor: 'border-[#113CCF]/30',
    tagline: 'The greatest stories, all in one place.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 1899,
    slug: 'max',
    name: 'Max',
    logo: 'https://image.tmdb.org/t/p/original/jbe4gVSfRlbPTdESXhEKpornsfu.jpg',
    color: '#002BE7',
    gradient: 'from-[#002BE7]/40 to-black',
    bgAccent: '#000424',
    borderColor: 'border-[#002BE7]/30',
    tagline: 'The one to watch.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 350,
    slug: 'apple-tv-plus',
    name: 'Apple TV+',
    logo: 'https://image.tmdb.org/t/p/original/mcbz1LgtErU9p4UdbZ0rG6RTWHX.jpg',
    color: '#ffffff',
    gradient: 'from-white/30 to-black',
    bgAccent: '#111111',
    borderColor: 'border-white/20',
    tagline: 'All Apple Originals.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 15,
    slug: 'hulu',
    name: 'Hulu',
    logo: 'https://image.tmdb.org/t/p/original/bxBlRPEPpMVDc4jMhSrTf2339DW.jpg',
    color: '#1CE783',
    gradient: 'from-[#1CE783]/40 to-black',
    bgAccent: '#022414',
    borderColor: 'border-[#1CE783]/30',
    tagline: 'All the TV you love.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 531,
    slug: 'paramount-plus',
    name: 'Paramount+',
    logo: 'https://image.tmdb.org/t/p/original/h5DcR0J2EESLitnhR8xLG1QymTE.jpg',
    color: '#0064FF',
    gradient: 'from-[#0064FF]/40 to-black',
    bgAccent: '#000f26',
    borderColor: 'border-[#0064FF]/30',
    tagline: 'A Mountain of Entertainment.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'major',
  },

  // REGIONAL POWERHOUSES
  {
    id: "122|532|2336",
    slug: 'jiohotstar',
    name: 'JioHotstar',
    logo: '/logos/jiohotstar-real.png',
    color: '#8B5CF6',
    gradient: 'from-[#8B5CF6]/60 via-[#EC4899]/30 to-black',
    bgAccent: '#120722',
    borderColor: 'border-[#8B5CF6]/40',
    tagline: 'Entertainment ka Naya Daur.',
    region: 'IN',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 237,
    slug: 'sonyliv',
    name: 'SonyLIV',
    logo: 'https://image.tmdb.org/t/p/original/3973zlBbBXdXxaWqRWzGG2GYxbT.jpg',
    color: '#00B1B0',
    gradient: 'from-[#00B1B0]/40 to-black',
    bgAccent: '#001a1a',
    borderColor: 'border-[#00B1B0]/30',
    tagline: 'We LIV to Entertain.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 232,
    slug: 'zee5',
    name: 'ZEE5',
    logo: 'https://image.tmdb.org/t/p/original/gP67NRy1ShUJilrzMsbOmEmdmcv.jpg',
    color: '#8230C6',
    gradient: 'from-[#8230C6]/40 to-black',
    bgAccent: '#13071f',
    borderColor: 'border-[#8230C6]/30',
    tagline: 'Anytime. Anywhere.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: "595|2059",
    slug: 'eros-now',
    name: 'Eros Now',
    logo: '/logos/erosnow-real.png',
    color: '#F48220',
    gradient: 'from-[#F48220]/40 to-black',
    bgAccent: '#241305',
    borderColor: 'border-[#F48220]/30',
    tagline: 'Bollywood and beyond.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: "226|515|1898",
    slug: 'mx-player',
    name: 'MX Player',
    logo: '/logos/mx-player-real.png',
    color: '#0033CC',
    gradient: 'from-[#0033CC]/40 to-black',
    bgAccent: '#00081f',
    borderColor: 'border-[#0033CC]/30',
    tagline: 'Everytainment.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: "235|315|2112",
    slug: 'altbalaji',
    name: 'ALTT',
    logo: '/logos/altbalaji-altt.png',
    color: '#E82A3A',
    gradient: 'from-[#E82A3A]/40 to-black',
    bgAccent: '#240608',
    borderColor: 'border-[#E82A3A]/30',
    tagline: 'Original stories.',
    region: 'IN',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 283,
    slug: 'crunchyroll',
    name: 'Crunchyroll',
    logo: 'https://image.tmdb.org/t/p/original/fzN5Jok5Ig1eJ7gyNGoMhnLSCfh.jpg',
    color: '#F47521',
    gradient: 'from-[#F47521]/40 to-black',
    bgAccent: '#241004',
    borderColor: 'border-[#F47521]/30',
    tagline: 'Everything Anime.',
    region: 'US',
    hasTrending: true,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 381,
    slug: 'canal-plus',
    name: 'Canal+',
    logo: '/logos/canal-plus.jpg',
    color: '#000000',
    gradient: 'from-zinc-800/60 to-black',
    bgAccent: '#111111',
    borderColor: 'border-zinc-700/50',
    tagline: 'Créateur de contenu.',
    region: 'FR',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 76,
    slug: 'viaplay',
    name: 'Viaplay',
    logo: '/logos/viaplay.jpg',
    color: '#FF1232',
    gradient: 'from-[#FF1232]/40 to-black',
    bgAccent: '#1f0003',
    borderColor: 'border-[#FF1232]/30',
    tagline: 'Nordic storytelling.',
    region: 'SE',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 38,
    slug: 'bbc-iplayer',
    name: 'BBC iPlayer',
    logo: 'https://image.tmdb.org/t/p/original/nc8Tpsr8SqCbsTUogPDD06gGzB3.jpg',
    color: '#E5004F',
    gradient: 'from-[#E5004F]/40 to-black',
    bgAccent: '#26000d',
    borderColor: 'border-[#E5004F]/30',
    tagline: 'The biggest new releases.',
    region: 'GB',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: "49|84|2284",
    slug: 'u-next',
    name: 'U-NEXT',
    logo: 'https://image.tmdb.org/t/p/original/27WMfRN7pQE3j5Khm8fPM7vYyLV.jpg',
    color: '#21C4D4',
    gradient: 'from-[#21C4D4]/40 to-black',
    bgAccent: '#031c1e',
    borderColor: 'border-[#21C4D4]/30',
    tagline: 'Unlimited entertainment.',
    region: 'JP',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 356,
    slug: 'wavve',
    name: 'Wavve',
    logo: '/logos/wavve.jpg',
    color: '#013DFF',
    gradient: 'from-[#013DFF]/40 to-black',
    bgAccent: '#000926',
    borderColor: 'border-[#013DFF]/30',
    tagline: 'Just dive in.',
    region: 'KR',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: "151|197|1852|2323",
    slug: 'britbox',
    name: 'BritBox',
    logo: 'https://image.tmdb.org/t/p/original/8oA7IcDNNUtBa9JYB5kQ8hrDz5o.jpg',
    color: '#000B2B',
    gradient: 'from-[#000B2B]/80 to-black',
    bgAccent: '#000105',
    borderColor: 'border-[#000B2B]/50',
    tagline: 'The biggest collection of British TV.',
    region: 'UK',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },

  // NICHE / FREE
  {
    id: 73,
    slug: 'tubi-tv',
    name: 'Tubi',
    logo: 'https://image.tmdb.org/t/p/original/zLYr7OPvpskMA4S79E3vlCi71iC.jpg',
    color: '#FF4F00',
    gradient: 'from-[#FF4F00]/40 to-black',
    bgAccent: '#260c00',
    borderColor: 'border-[#FF4F00]/30',
    tagline: 'Free movies and TV.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 300,
    slug: 'pluto-tv',
    name: 'Pluto TV',
    logo: 'https://image.tmdb.org/t/p/original/dB8G41Q6tSL5NBisrIeqByfepBc.jpg',
    color: '#F3E400',
    gradient: 'from-[#F3E400]/20 to-black',
    bgAccent: '#242200',
    borderColor: 'border-[#F3E400]/20',
    tagline: 'Drop in. It\'s free.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 11,
    slug: 'mubi',
    name: 'MUBI',
    logo: 'https://image.tmdb.org/t/p/original/x570VpH2C9EKDf1riP83rYc5dnL.jpg',
    color: '#15065e',
    gradient: 'from-[#15065e]/60 to-black',
    bgAccent: '#03010f',
    borderColor: 'border-[#15065e]/50',
    tagline: 'Hand-picked cinema.',
    region: 'US',
    hasTrending: false,
    categories: ['movie'],
    tier: 'niche',
  },
  {
    id: 99,
    slug: 'shudder',
    name: 'Shudder',
    logo: 'https://image.tmdb.org/t/p/original/vEtdiYRPRbDCp1Tcn3BEPF1Ni76.jpg',
    color: '#FF0000',
    gradient: 'from-red-600/40 to-black',
    bgAccent: '#1a0000',
    borderColor: 'border-red-600/30',
    tagline: 'Scream-worthy horror.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 258,
    slug: 'criterion-channel',
    name: 'Criterion Channel',
    logo: 'https://image.tmdb.org/t/p/original/yhrtzYd43pFIhRq0ruO8umJPuyn.jpg',
    color: '#8A7D6C',
    gradient: 'from-[#8A7D6C]/40 to-black',
    bgAccent: '#141210',
    borderColor: 'border-[#8A7D6C]/30',
    tagline: 'Classic and contemporary films.',
    region: 'US',
    hasTrending: false,
    categories: ['movie'],
    tier: 'niche',
  },
  {
    id: 538,
    slug: 'plex',
    name: 'Plex',
    logo: 'https://image.tmdb.org/t/p/original/vLZKlXUNDcZR7ilvfY9Wr9k80FZ.jpg',
    color: '#EBAF00',
    gradient: 'from-[#EBAF00]/30 to-black',
    bgAccent: '#241b00',
    borderColor: 'border-[#EBAF00]/20',
    tagline: 'Your media, your way.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 190,
    slug: 'curiosity-stream',
    name: 'Curiosity Stream',
    logo: 'https://image.tmdb.org/t/p/original/oR1aNm1Qu9jQBkW4VrGPWhqbC3P.jpg',
    color: '#FFB81C',
    gradient: 'from-[#FFB81C]/30 to-black',
    bgAccent: '#261b04',
    borderColor: 'border-[#FFB81C]/20',
    tagline: 'Feed your curiosity.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 386,
    slug: 'peacock',
    name: 'Peacock',
    logo: 'https://image.tmdb.org/t/p/original/2aGrp1xw3qhwCYvNGAJZPdjfeeX.jpg',
    color: '#00A850',
    gradient: 'from-[#00A850]/40 to-black',
    bgAccent: '#001a0c',
    borderColor: 'border-[#00A850]/30',
    tagline: 'Watch for free. Upgrade for more.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: "188|192|235|2528",
    slug: 'youtube-premium',
    name: 'YouTube Premium',
    logo: 'https://image.tmdb.org/t/p/original/rMb93u1tBeErSYLv79zSTR07UdO.jpg',
    color: '#FF0000',
    gradient: 'from-red-600/40 to-black',
    bgAccent: '#1a0000',
    borderColor: 'border-red-600/30',
    tagline: 'Ad-free and offline.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 344,
    slug: 'rakuten-viki',
    name: 'Rakuten Viki',
    logo: 'https://image.tmdb.org/t/p/original/73uV3YooOA8gD9YQTXFj2XakZWA.jpg',
    color: '#0862d0',
    gradient: 'from-[#0862d0]/40 to-black',
    bgAccent: '#010e1f',
    borderColor: 'border-[#0862d0]/30',
    tagline: 'Global Asian Entertainment.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 97,
    slug: 'watcha',
    name: 'Watcha',
    logo: '/logos/watcha.jpg',
    color: '#FF0558',
    gradient: 'from-[#FF0558]/40 to-black',
    bgAccent: '#26000d',
    borderColor: 'border-[#FF0558]/30',
    tagline: 'Find your next favorite.',
    region: 'KR',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 584,
    slug: 'discovery-plus',
    name: 'discovery+',
    logo: 'https://image.tmdb.org/t/p/original/lgudHqEtTOzkMWlpTjU1oUyoUSZ.jpg',
    color: '#000000',
    gradient: 'from-blue-600/30 to-black',
    bgAccent: '#000a1a',
    borderColor: 'border-blue-600/30',
    tagline: 'Real life entertainment.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'major',
  },
  {
    id: 149,
    slug: 'movistar-plus',
    name: 'Movistar Plus+ Ficción Total',
    logo: '/logos/espn-plus.jpg',
    color: '#E31837',
    gradient: 'from-[#E31837]/40 to-black',
    bgAccent: '#210308',
    borderColor: 'border-[#E31837]/30',
    tagline: 'Ficción Total',
    region: 'ES',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 43,
    slug: 'starz',
    name: 'Starz',
    logo: 'https://image.tmdb.org/t/p/original/yIKwylTLP1u8gl84Is7FItpYLGL.jpg',
    color: '#000000',
    gradient: 'from-zinc-800/40 to-black',
    bgAccent: '#111111',
    borderColor: 'border-zinc-700/30',
    tagline: 'Obsessable.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: "37|1773|2624",
    slug: 'showtime',
    name: 'Showtime',
    logo: '/logos/showtime-anytime.png',
    color: '#E50914',
    gradient: 'from-red-700/40 to-black',
    bgAccent: '#1f0000',
    borderColor: 'border-red-700/30',
    tagline: 'Pushing boundaries.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'regional',
  },
  {
    id: 526,
    slug: 'amc-plus',
    name: 'AMC+',
    logo: 'https://image.tmdb.org/t/p/original/ovmu6uot1XVvsemM2dDySXLiX57.jpg',
    color: '#D4AF37',
    gradient: 'from-[#D4AF37]/30 to-black',
    bgAccent: '#1f1a08',
    borderColor: 'border-[#D4AF37]/20',
    tagline: 'The best of AMC.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
  {
    id: 87,
    slug: 'acorn-tv',
    name: 'Acorn TV',
    logo: 'https://image.tmdb.org/t/p/original/doCc555FPPgGtuaZJxf9QZVpIp5.jpg',
    color: '#1A4F41',
    gradient: 'from-[#1A4F41]/50 to-black',
    bgAccent: '#020d0a',
    borderColor: 'border-[#1A4F41]/40',
    tagline: 'World-class mysteries.',
    region: 'US',
    hasTrending: false,
    categories: ['movie', 'tv'],
    tier: 'niche',
  },
];
